version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: site-analyzer-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      # Enable auth and set default DB
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: sv-app
    volumes:
      - mongo-data-dev:/data/db
      - mongo-config-dev:/data/configdb
      # Auto-init scripts (create non-root application user, seed data, etc.)
      - ./docker/mongo-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional web UI for MongoDB. Uncomment to enable.
  # mongo-express:
  #   image: mongo-express:1.0.2-20
  #   restart: unless-stopped
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_SERVER: mongodb
  #   depends_on:
  #     - mongodb

volumes:
  mongo-data-dev:
  mongo-config-dev:
